### PR TITLE
Allow injection of CPPFLAGS/LDFLAGS

### PR DESCRIPTION
**Pull request by pb-cdunn**
We need to provide `-I` and `-L` for our zlib.

### CODE REVIEW

**Comment by armintoepfer** [comment]
:+1:

**Comment by lh3** [comment]
It is ok to add LDFLAGS.

However, CPPFLAGS is used for the C preprocessor only. It should not appear on the linking line. INCLUDES provides the header path. You should keep that.

**Comment by lh3** [comment]
By the way, [minimap2](https://github.com/lh3/minimap2) is more sensitive than minimap on pacbio read overlapping. Their usage, output and speed are similar.

**Comment by pb-cdunn** [comment]
@lh3, Updated per comments.

Note: In a Makefile, if you set `INCLUDES=-I.`, as in:
```mk
INCLUDES=-I.
main.o: main.c
    gcc -c $(INCLUDES) main.c
```

Then the following would override `INCLUDES`:
```sh
make INCLUDES=-Ifoo
# INCLUDES is still just "-Ifoo"; i.e. "-I." is gone!
```
With **GNU make**, you could do this (unfortunately to *append* instead of *prepend*):
```mk
INCLUDES+= -I.
```
Or this:
```mk
INCLUDES:= -I. $(INCLUDES)
```
But not with [**POSIX make**](http://www.unix.com/man-page/posix/1posix/make/).

Anyway, your build does not actually need `-I.` anyway, so I removed that line. Please take a look at the updated version.

**Comment by lh3** [comment]
Thanks. Merged.

**Comment by pb-cdunn** [comment]
Thank you, Dr. Li. And we will definitely try minimap2 when we have time.

**Pull request merged**
